name: Sync Core to VeroSleeves

on:
  push:
    branches:
      - main

jobs:
  filtered-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo1 (nest-kafka)
        uses: actions/checkout@v4

      - name: Create filtered export directory
        run: |
          mkdir ../filtered-export
          echo ".github/workflows/sync-repo.yml" > exclude.txt
          rsync -av --progress --exclude-from=exclude.txt . ../filtered-export

      - name: Push filtered content to VeroSleeves (repo2)
        run: |
          cd ../filtered-export
          git init
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote remove origin || true
          git remote add origin https://x-access-token:${{ secrets.SECRET_TOKEN }}@github.com/Metapolitanltd/VeroSleeves.git
          git checkout -b main
          git add .
          git commit -m "Sync Core from nest-kafka"
          git push origin main --force